```toml
[build]
  command = "npm install"
  publish = "public"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "/.netlify/functions/api/uploads/:splat"
  status = 200
  force = true
```
